### PR TITLE
Allow to compile with openssl 1.0.1

### PR DESCRIPTION
**Pull request by normanmaurer**
Motivation:

After upgrading the gcc version of the CI the build failed with:

[07:48:57][io.netty:netty-tcnative] [INFO] src/sslcontext.c: In function 'cert_requested':
[07:48:57][io.netty:netty-tcnative] [INFO] src/sslcontext.c:1438:13: error: implicit declaration of function 'SSL_add0_chain_cert' [-Werror=implicit-function-declaration]
[07:48:57][io.netty:netty-tcnative] [INFO]          if (SSL_add0_chain_cert(ssl, sk_X509_value(chain, i)) <= 0) {

This is due a missing ifdef condition for openssl < 1.0.2.

Modifications:

Fix ifdef

Result:

Be able to compile against openssl 1.0.1 again with newer gcc versions.

### CODE REVIEW

**Comment by normanmaurer** [comment]
See also:

https://garage.netty.io/teamcity/viewLog.html?buildId=18601&buildTypeId=pulls_netty_tcnative&tab=buildLog#_focus=386

@Scottmitch after this one is merged I also want to investigate in using weak linking for GCC as we discussed when I was in california

**Comment by normanmaurer** [comment]
Also just to make it more clear it failed because `SSL_add0_chain_cert` only exists in openssl >= 1.0.2

**Comment by normanmaurer** [comment]
Cherry-picked into master (058c38a4a1012d1f189eacc5691349eff7067862)
