### ISSUE TITLE
Compile errors with Fork23 and OpenSSL 1.1.0c

### ISSUE THREAD

**Issue by floragunncom** [netty/netty-tcnative#218]
Try to statically compile netty tcnative 1.1.33.Fork23 with OpenSSL 1.1.0c on ubuntu 14.04 but it fails. With OpenSSL 1.0.2j its working.

So i assume the dynamically linked version will also not work with OpenSSL 1.1.0c?

gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
<pre>
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./src -O3 -Werror -DHAVE_OPENSSL -I/home/ubuntu/search-guard-nettytcnative-static/netty-tcnative/openssl-static/target/ssl/include -I/home/ubuntu/search-guard-nettytcnative-static/netty-tcnative/openssl-static/target/apr/include/apr-1 -D_LARGEFILE64_SOURCE -I/usr/lib/jvm/jdk1.8.0/include -I/usr/lib/jvm/jdk1.8.0/include/linux -c src/ssl.c  -fPIC -DPIC -o src/.libs/ssl.o
src/ssl.c: In function 'ssl_init_cleanup':
src/ssl.c:316:5: error: 'ERR_remove_state' is deprecated (declared at /home/ubuntu/search-guard-nettytcnative-static/netty-tcnative/openssl-static/target/ssl/include/openssl/err.h:247) [-Werror=deprecated-declarations]
    ERR_remove_state(0);
     ^
src/ssl.c: In function 'SSL_BIO_close':
src/ssl.c:865:11: error: dereferencing pointer to incomplete type
     if (bi->ptr != NULL && (bi->flags & SSL_BIO_FLAG_CALLBACK)) {
           ^
src/ssl.c:865:31: error: dereferencing pointer to incomplete type
     if (bi->ptr != NULL && (bi->flags & SSL_BIO_FLAG_CALLBACK)) {
                               ^
src/ssl.c:866:37: error: dereferencing pointer to incomplete type
         BIO_JAVA *j = (BIO_JAVA *)bi->ptr;
                                     ^
src/ssl.c: In function 'SSL_BIO_doref':
src/ssl.c:883:11: error: dereferencing pointer to incomplete type
     if (bi->ptr != NULL && (bi->flags & SSL_BIO_FLAG_CALLBACK)) {
           ^
src/ssl.c:883:31: error: dereferencing pointer to incomplete type
     if (bi->ptr != NULL && (bi->flags & SSL_BIO_FLAG_CALLBACK)) {
                               ^
src/ssl.c:884:37: error: dereferencing pointer to incomplete type
         BIO_JAVA *j = (BIO_JAVA *)bi->ptr;
                                     ^
src/ssl.c: In function 'jbs_new':
src/ssl.c:898:7: error: dereferencing pointer to incomplete type
     bi->shutdown = 1;
       ^
src/ssl.c:899:7: error: dereferencing pointer to incomplete type
     bi->init     = 0;
       ^
src/ssl.c:900:7: error: dereferencing pointer to incomplete type
     bi->num      = -1;
       ^
src/ssl.c:901:7: error: dereferencing pointer to incomplete type
     bi->ptr      = (char *)j;
       ^
src/ssl.c: In function 'jbs_free':
src/ssl.c:913:11: error: dereferencing pointer to incomplete type
     if (bi->ptr != NULL) {
           ^
src/ssl.c:914:27: error: dereferencing pointer to incomplete type
         j = (BIO_JAVA *)bi->ptr;
                           ^
src/ssl.c:915:15: error: dereferencing pointer to incomplete type
         if (bi->init) {
               ^
src/ssl.c:916:15: error: dereferencing pointer to incomplete type
             bi->init = 0;
               ^
In file included from /home/ubuntu/search-guard-nettytcnative-static/netty-tcnative/openssl-static/target/ssl/include/openssl/comp.h:16:0,
                 from /home/ubuntu/search-guard-nettytcnative-static/netty-tcnative/openssl-static/target/ssl/include/openssl/ssl.h:47,
                 from src/ssl_private.h:47,
                 from src/ssl.c:29:
src/ssl.c:920:24: error: dereferencing pointer to incomplete type
         OPENSSL_free(bi->ptr);
                        ^
/home/ubuntu/search-guard-nettytcnative-static/netty-tcnative/openssl-static/target/ssl/include/openssl/crypto.h:136:21: note: in definition of macro 'OPENSSL_free'
         CRYPTO_free(addr, OPENSSL_FILE, OPENSSL_LINE)
                     ^
src/ssl.c:922:7: error: dereferencing pointer to incomplete type
     bi->ptr = NULL;
       ^
src/ssl.c: In function 'jbs_write':
src/ssl.c:930:10: error: dereferencing pointer to incomplete type
     if (b->init && in != NULL) {
          ^
src/ssl.c:931:36: error: dereferencing pointer to incomplete type
         BIO_JAVA *j = (BIO_JAVA *)b->ptr;
                                    ^
src/ssl.c: In function 'jbs_read':
src/ssl.c:956:10: error: dereferencing pointer to incomplete type
     if (b->init && out != NULL) {
          ^
src/ssl.c:957:36: error: dereferencing pointer to incomplete type
         BIO_JAVA *j = (BIO_JAVA *)b->ptr;
                                    ^
src/ssl.c: In function 'jbs_puts':
src/ssl.c:986:10: error: dereferencing pointer to incomplete type
     if (b->init && in != NULL) {
          ^
src/ssl.c:987:26: error: dereferencing pointer to incomplete type
         j = (BIO_JAVA *)b->ptr;
                          ^
src/ssl.c: In function 'jbs_gets':
src/ssl.c:1004:10: error: dereferencing pointer to incomplete type
     if (b->init && out != NULL) {
          ^
src/ssl.c:1005:26: error: dereferencing pointer to incomplete type
         j = (BIO_JAVA *)b->ptr;
                          ^
src/ssl.c: At top level:
src/ssl.c:1037:1: error: variable 'jbs_methods' has initializer but incomplete type
 static BIO_METHOD jbs_methods = {
 ^
src/ssl.c:1038:5: error: excess elements in struct initializer [-Werror]
     BIO_TYPE_FILE,
     ^
src/ssl.c:1038:5: error: (near initialization for 'jbs_methods') [-Werror]
src/ssl.c:1039:5: error: excess elements in struct initializer [-Werror]
     "Java Callback",
     ^
src/ssl.c:1039:5: error: (near initialization for 'jbs_methods') [-Werror]
src/ssl.c:1040:5: error: excess elements in struct initializer [-Werror]
     jbs_write,
     ^
src/ssl.c:1040:5: error: (near initialization for 'jbs_methods') [-Werror]
src/ssl.c:1041:5: error: excess elements in struct initializer [-Werror]
     jbs_read,
     ^
src/ssl.c:1041:5: error: (near initialization for 'jbs_methods') [-Werror]
src/ssl.c:1042:5: error: excess elements in struct initializer [-Werror]
     jbs_puts,
     ^
src/ssl.c:1042:5: error: (near initialization for 'jbs_methods') [-Werror]
src/ssl.c:1043:5: error: excess elements in struct initializer [-Werror]
     jbs_gets,
     ^
src/ssl.c:1043:5: error: (near initialization for 'jbs_methods') [-Werror]
src/ssl.c:1044:5: error: excess elements in struct initializer [-Werror]
     jbs_ctrl,
     ^
src/ssl.c:1044:5: error: (near initialization for 'jbs_methods') [-Werror]
src/ssl.c:1045:5: error: excess elements in struct initializer [-Werror]
     jbs_new,
     ^
src/ssl.c:1045:5: error: (near initialization for 'jbs_methods') [-Werror]
src/ssl.c:1046:5: error: excess elements in struct initializer [-Werror]
     jbs_free,
     ^
src/ssl.c:1046:5: error: (near initialization for 'jbs_methods') [-Werror]
src/ssl.c:1048:1: error: excess elements in struct initializer [-Werror]
 };
 ^
src/ssl.c:1048:1: error: (near initialization for 'jbs_methods') [-Werror]
src/ssl.c: In function 'Java_org_apache_tomcat_jni_SSL_newBIO':
src/ssl.c:1083:24: error: dereferencing pointer to incomplete type
     j = (BIO_JAVA *)bio->ptr;
                        ^
src/ssl.c:1103:8: error: dereferencing pointer to incomplete type
     bio->init  = 1;
        ^
src/ssl.c:1104:8: error: dereferencing pointer to incomplete type
     bio->flags = SSL_BIO_FLAG_CALLBACK;
        ^
cc1: all warnings being treated as errors
make: *** [src/ssl.lo] Error 1
rc: 2
</pre>

**Comment by floragunncom** [comment]
Fork 25 does also fail with

<pre>
[INFO] libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./src -O3 -Werror -fno-omit-frame-pointer -DHAVE_OPENSSL -I/home/ubuntu/search-guard-nettytcnative-static/netty-tcnative/openssl-static/target/ssl/include -I/home/ubuntu/search-guard-nettytcnative-static/netty-tcnative/openssl-static/target/apr/include/apr-1 -D_LARGEFILE64_SOURCE -I/usr/lib/jvm/jdk1.8.0/include -I/usr/lib/jvm/jdk1.8.0/include/linux -c src/ssl.c  -fPIC -DPIC -o src/.libs/ssl.o
[INFO] src/ssl.c: In function 'SSL_BIO_doref':
[INFO] src/ssl.c:908:37: error: dereferencing pointer to incomplete type
[INFO]          BIO_JAVA *j = (BIO_JAVA *)bi->ptr;
[INFO]                                      ^
[INFO] make: *** [src/ssl.lo] Error 1
</pre>

**Comment by Scottmitch** [comment]
Please try building against the `master` branch. Netty will be transitioning to the `master` branch soon and that is where we will support `1.1.x` OpenSSL APIs.

**Comment by floragunncom** [comment]
Also no luck with master branch (on cbd38f31f250bd5329b3dfd535c89e4ae7b1c431)

<pre>
lib/jvm/jdk1.8.0/include -I/usr/lib/jvm/jdk1.8.0/include/linux -c -o src/sslcontext.lo src/sslcontext.c
[INFO] libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I./src -O3 -Werror -fno-omit-frame-pointer -Wunused-variable -DHAVE_OPENSSL -I/home/ubuntu/search-guard-nettytcnative-static/netty-tcnative/openssl-static/target/ssl/include -I/home/ubuntu/search-guard-nettytcnative-static/netty-tcnative/openssl-static/target/apr/include/apr-1 -D_LARGEFILE64_SOURCE -I/usr/lib/jvm/jdk1.8.0/include -I/usr/lib/jvm/jdk1.8.0/include/linux -c src/sslcontext.c  -fPIC -DPIC -o src/.libs/sslcontext.o
[INFO] src/sslcontext.c: In function 'Java_io_netty_tcnative_jni_SSLContext_make':
[INFO] src/sslcontext.c:115:13: error: 'TLSv1_2_client_method' is deprecated (declared at /home/ubuntu/search-guard-nettytcnative-static/netty-tcnative/openssl-static/target/ssl/include/openssl/ssl.h:1610) [-Werror=deprecated-declarations]
[INFO]              ctx = SSL_CTX_new(TLSv1_2_client_method());
[INFO]              ^
[INFO] src/sslcontext.c:117:13: error: 'TLSv1_2_server_method' is deprecated (declared at /home/ubuntu/search-guard-nettytcnative-static/netty-tcnative/openssl-static/target/ssl/include/openssl/ssl.h:1609) [-Werror=deprecated-declarations]
[INFO]              ctx = SSL_CTX_new(TLSv1_2_server_method());
[INFO]              ^
[INFO] src/sslcontext.c:119:13: error: 'TLSv1_2_method' is deprecated (declared at /home/ubuntu/search-guard-nettytcnative-static/netty-tcnative/openssl-static/target/ssl/include/openssl/ssl.h:1608) [-Werror=deprecated-declarations]
[INFO]              ctx = SSL_CTX_new(TLSv1_2_method());
[INFO]              ^
[INFO] src/sslcontext.c:125:13: error: 'TLSv1_1_client_method' is deprecated (declared at /home/ubuntu/search-guard-nettytcnative-static/netty-tcnative/openssl-static/target/ssl/include/openssl/ssl.h:1604) [-Werror=deprecated-declarations]
[INFO]              ctx = SSL_CTX_new(TLSv1_1_client_method());
[INFO]              ^
[INFO] src/sslcontext.c:127:13: error: 'TLSv1_1_server_method' is deprecated (declared at /home/ubuntu/search-guard-nettytcnative-static/netty-tcnative/openssl-static/target/ssl/include/openssl/ssl.h:1603) [-Werror=deprecated-declarations]
[INFO]              ctx = SSL_CTX_new(TLSv1_1_server_method());
[INFO]              ^
[INFO] src/sslcontext.c:129:13: error: 'TLSv1_1_method' is deprecated (declared at /home/ubuntu/search-guard-nettytcnative-static/netty-tcnative/openssl-static/target/ssl/include/openssl/ssl.h:1602) [-Werror=deprecated-declarations]
[INFO]              ctx = SSL_CTX_new(TLSv1_1_method());
[INFO]              ^
[INFO] src/sslcontext.c:135:13: error: 'TLSv1_client_method' is deprecated (declared at /home/ubuntu/search-guard-nettytcnative-static/netty-tcnative/openssl-static/target/ssl/include/openssl/ssl.h:1598) [-Werror=deprecated-declarations]
[INFO]              ctx = SSL_CTX_new(TLSv1_client_method());
[INFO]              ^
[INFO] src/sslcontext.c:137:13: error: 'TLSv1_server_method' is deprecated (declared at /home/ubuntu/search-guard-nettytcnative-static/netty-tcnative/openssl-static/target/ssl/include/openssl/ssl.h:1597) [-Werror=deprecated-declarations]
[INFO]              ctx = SSL_CTX_new(TLSv1_server_method());
[INFO]              ^
[INFO] src/sslcontext.c:139:13: error: 'TLSv1_method' is deprecated (declared at /home/ubuntu/search-guard-nettytcnative-static/netty-tcnative/openssl-static/target/ssl/include/openssl/ssl.h:1596) [-Werror=deprecated-declarations]
[INFO]              ctx = SSL_CTX_new(TLSv1_method());
[INFO]              ^
[INFO] src/sslcontext.c:167:17: error: 'TLSv1_2_client_method' is deprecated (declared at /home/ubuntu/search-guard-nettytcnative-static/netty-tcnative/openssl-static/target/ssl/include/openssl/ssl.h:1610) [-Werror=deprecated-declarations]
[INFO]                  ctx = SSL_CTX_new(TLSv1_2_client_method());
[INFO]                  ^
[INFO] src/sslcontext.c:169:17: error: 'TLSv1_2_server_method' is deprecated (declared at /home/ubuntu/search-guard-nettytcnative-static/netty-tcnative/openssl-static/target/ssl/include/openssl/ssl.h:1609) [-Werror=deprecated-declarations]
[INFO]                  ctx = SSL_CTX_new(TLSv1_2_server_method());
[INFO]                  ^
[INFO] src/sslcontext.c:171:17: error: 'TLSv1_2_method' is deprecated (declared at /home/ubuntu/search-guard-nettytcnative-static/netty-tcnative/openssl-static/target/ssl/include/openssl/ssl.h:1608) [-Werror=deprecated-declarations]
[INFO]                  ctx = SSL_CTX_new(TLSv1_2_method());
[INFO]                  ^
[INFO] src/sslcontext.c:175:17: error: 'TLSv1_1_client_method' is deprecated (declared at /home/ubuntu/search-guard-nettytcnative-static/netty-tcnative/openssl-static/target/ssl/include/openssl/ssl.h:1604) [-Werror=deprecated-declarations]
[INFO]                  ctx = SSL_CTX_new(TLSv1_1_client_method());
[INFO]                  ^
[INFO] src/sslcontext.c:177:17: error: 'TLSv1_1_server_method' is deprecated (declared at /home/ubuntu/search-guard-nettytcnative-static/netty-tcnative/openssl-static/target/ssl/include/openssl/ssl.h:1603) [-Werror=deprecated-declarations]
[INFO]                  ctx = SSL_CTX_new(TLSv1_1_server_method());
[INFO]                  ^
[INFO] src/sslcontext.c:179:17: error: 'TLSv1_1_method' is deprecated (declared at /home/ubuntu/search-guard-nettytcnative-static/netty-tcnative/openssl-static/target/ssl/include/openssl/ssl.h:1602) [-Werror=deprecated-declarations]
[INFO]                  ctx = SSL_CTX_new(TLSv1_1_method());
[INFO]                  ^
[INFO] src/sslcontext.c:183:17: error: 'TLSv1_client_method' is deprecated (declared at /home/ubuntu/search-guard-nettytcnative-static/netty-tcnative/openssl-static/target/ssl/include/openssl/ssl.h:1598) [-Werror=deprecated-declarations]
[INFO]                  ctx = SSL_CTX_new(TLSv1_client_method());
[INFO]                  ^
[INFO] src/sslcontext.c:185:17: error: 'TLSv1_server_method' is deprecated (declared at /home/ubuntu/search-guard-nettytcnative-static/netty-tcnative/openssl-static/target/ssl/include/openssl/ssl.h:1597) [-Werror=deprecated-declarations]
[INFO]                  ctx = SSL_CTX_new(TLSv1_server_method());
[INFO]                  ^
[INFO] src/sslcontext.c:187:17: error: 'TLSv1_method' is deprecated (declared at /home/ubuntu/search-guard-nettytcnative-static/netty-tcnative/openssl-static/target/ssl/include/openssl/ssl.h:1596) [-Werror=deprecated-declarations]
[INFO]                  ctx = SSL_CTX_new(TLSv1_method());
[INFO]                  ^
[INFO] src/sslcontext.c: In function 'SSL_cert_verify':
[INFO] src/sslcontext.c:1211:29: error: dereferencing pointer to incomplete type
[INFO]      STACK_OF(X509) *sk = ctx->untrusted;
[INFO]                              ^
[INFO] cc1: all warnings being treated as errors
[INFO] make: *** [src/sslcontext.lo] Error 1
[INFO] rc: 2
</pre>

**Comment by normanmaurer** [comment]
Will have a look

**Comment by nename0** [comment]
Related to #249

**Comment by normanmaurer** [comment]
Fixed by https://github.com/netty/netty-tcnative/pull/249
