### ISSUE TITLE
Unable to use pre-built binaries on alpine linux

### ISSUE THREAD

**Issue by ankurcha** [netty/netty-tcnative#111]
I am trying to use the netty-tcnative libraries for my grpc application in a docker container. When i use the prebuilt binary I get the following error:

``` bash
Inconsistency detected by ld.so: dl-lookup.c: 128: check_match: Assertion `version->filename == ((void *)0) || ! _dl_name_match_p (version->filename, map)' failed!
```

**Comment by normanmaurer** [comment]
we release versions build on centos and debian. I guess you will need to build it by your own for alpine.

**Comment by dimitarg** [comment]
Assuming an alpine docker image which has an oracle jdk 8 installed, and netty-tcnative available under /opt/data/netty-tcnative (perhaps through a shared volume in the host, if you don't want to bother installing git on the alpine image), here is a setup which let me build netty-tcnative successfully:

```
MAVEN_VERSION=3.3.3 \
 && cd /usr/share \
 && wget http://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz -O - | tar xzf - \
 && mv /usr/share/apache-maven-$MAVEN_VERSION /usr/share/maven \
 && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn


export MAVEN_HOME=/usr/share/maven

cd /opt/data/netty-tcnative/

apk update

apk add autoconf

apk add automake

apk add libtool 

apk add alpine-sdk

apk add apr-util

apk add apr-util-dev

apk add build-base gcc abuild binutils binutils-doc gcc-doc

apk add cmake cmake-doc

apk add ninja

apk add go
```

, and then 

```mvn clean install```


@ankurcha and anyone else interested, I will let you know if the end result actually works. My usecase though is netty http2 server with openssl and epoll, I don't know if that would show that grpc works. We use netty directly though, no grpc involved in the test.

**Comment by dimitarg** [comment]
The built native jar as desribed above, under openssl-dynamic/target/netty-tcnative-<version>-linux-x86_64.jar , works for me, if I use the following, in a runtime image based FROM jeanblanchard/java:jdk-8:

```
run 'apk update'
run 'apk add apr-util apr-util-dev libuuid'
```

It's very important to change the base image only if you know what you are doing otherwise you might end up not finding libuuid during tcnative load.

Hope this helps. Hopefully I get the time to provide this in a matter more automated than github comments someday.

Cheers, Dimitar

**Comment by flozano** [comment]
This issue has Fork17 milestone assigned, does it mean it is fixed in Fork17? I can't find the proper alpine linux jar in maven for this version...

Building is a pretty complex process, and it seems alpine is gaining a lot of momentum in docker containers. It would be really great if the binaries were built by default.

**Comment by Scottmitch** [comment]
this issue has not been resolved ... as of now we don't publish artifacts built from alpine.

**Comment by dimitarg** [comment]
[netty-tcnative-1.1.33.Fork15-linux-x86_64_alpine.jar.zip](https://github.com/netty/netty-tcnative/files/295126/netty-tcnative-1.1.33.Fork15-linux-x86_64_alpine.jar.zip)

Here's the result of the build procedure I described above, for fork15, if you just wanna kick the tires.

**Comment by flozano** [comment]
Thanks a lot for the effort @dimitarg.

For now I'll have to stick to a more standard glibc-based docker image, but I'm definitely interested in trying to run my components with alpine again when tcnative binaries are part of "official" build/publish process for netty-tcnative.

**Comment by pires** [comment]
@dimitarg thanks to your work I've [automated the build of binaries for Alpine](https://github.com/pires/netty-tcnative-alpine) with Docker.
To whomever needs this, feel free to use and abuse.

**Comment by dimitarg** [comment]
@pires based on your work I have this [automated via gradle]. Thanks! (https://github.com/dimitarg/build_tcnative_alpine/). 
@normanmaurer If you folks decide to support this some day, we've now automated it down to a single command. It's written in gradle, though. I did not feel like writing such an involved thing in maven.

**Comment by nmittler** [comment]
Thanks @dimitarg and @pires ... This looks great!

@normanmaurer @trustin  @Scottmitch perhaps we should resume the discussion of switching gradle? The simplicity of this configuration is in pretty stark contrast to the hackery required to make tcnative build in Maven. I think it's pretty clear at this point that the complexity of this project isn't well suited for Maven.

**Comment by trustin** [comment]
+1 for switching to Gradle due to its customizability and speed.

**Comment by pires** [comment]
@nmittler @trustin what @dimitarg did was to use Gradle to automate the build of [my container that builds `netty-tcnative`](https://github.com/pires/netty-tcnative-alpine). On that container, [I'm still using Maven to build the Java artifacts](https://github.com/pires/netty-tcnative-alpine/blob/master/compile.sh#L6).

That said, I have nothing to add in favor or against changing this project build tool.

**Comment by Scottmitch** [comment]
i'm not opposed to switching but I would like to understand the concrete value. Simplicity, customization, speed are all good reasons and I'm interested to see a PR with these characteristics. One issue I have experienced with gradle (possibly pre 3.0) is order of execution between plugins/tasks can sometimes be less than intuitive.

Also who ever is willing to undertake this effort should consider updating existing docs.

**Comment by pires** [comment]
LibreSSL 2.4.2 doesn't compile on Alpine so Fork21 and Fork22 won't compile as well, with the following error:
```
     [exec]   CC       compat/getentropy_linux.lo
     [exec] Makefile:3615: recipe for target 'compat/getentropy_linux.lo' failed
     [exec] make[1]: Leaving directory '/netty-tcnative/libressl-static/target/libressl-2.4.2/crypto'
     [exec] Makefile:452: recipe for target 'all-recursive' failed
     [exec] compat/getentropy_linux.c:31:26: fatal error: linux/sysctl.h: No such file or directory
     [exec] compilation terminated.
     [exec] make[1]: *** [compat/getentropy_linux.lo] Error 1
     [exec] make: *** [all-recursive] Error 1
```

Change introduced in https://github.com/netty/netty-tcnative/commit/fd95303caaeb02717821013d6bf86e537f085869.

Also, I spotted this from ~1yr ago, https://github.com/libressl-portable/portable/issues/96.

**Comment by anuraaga** [comment]
Hello - was wondering, is the current release process for tcnative documented anywhere? Checked the wiki and couldn't find it so wondering if it's "start up a bunch of VMs on the build machine and manually do things".

I think using docker for linux versions would make the build simpler, while also making it easy to add more linux variants like alpine. If this makes sense, I'd be happy to help contribute but need to understand the current process first (the alpine version would probably just steal straight from the links in this thread, and the centos / debian versions would be small modifications after that ;) ).

alpine linux is very popular in docker containers (I've heard of it being the "official linux" for docker but am not sure on this), docker is popular for microservices, and netty is commonly used for microservices - so IMO supporting alpine officially is very reasonable, compared to maybe more esoteric environments. Would love to help make it happen anyway I can, short of hosting binaries myself as alpine seems popular enough to deserve an official, trusted version.

**Comment by trustin** [comment]
@anuraaga Sounds like a great idea to me, although we will have to deal with Windows as well as a part of the process. I'm not actually familiar with the current netty-tcnative release process, so @normanmaurer could provide some guide here.

**Comment by trustin** [comment]
Had a chance to talk to @anuraaga and it seems like Alpine Linux is not using GLIBC but [musl libc](https://www.musl-libc.org/) interestingly, and that's why our static builds do not work with it.

**Comment by stresler** [comment]
@pires I'm trying to compile your alpine version (thanks!) apr has moved to 1.6.2 and I can make that change, but then I stumbled across this https://github.com/netty/netty-tcnative/pull/255

I don't have time to delve into that, but will that glibc dependency kill musl compatibility in the future?

**Comment by gyndav** [comment]
@pires do you still publish the built versions somewhere? Didn't not managed to compile it entirely tho.

**Comment by pires** [comment]
gyndav yes https://github.com/pires/netty-tcnative-alpine/releases 2.0.6 is the latest but one can easily change that.

**Comment by pires** [comment]
@normanmaurer why docker-compose instead of multi-stage builds?

**Comment by philicious** [comment]
I would like to express strong interest in an alpine-version available from maven. 
Its just to cumbersome building it yourself if you do wanna use alpine images

**Comment by hc-codersatlas** [comment]
Are there any other issues besides glibc? So if we manually install glibc on Alpine it'll still work?

**Comment by ejona86** [comment]
I don't think glibc is even an issue now. I think you just need `apk update && apk add libc6-compat`. That's what it seemed like when I tested for grpc: https://github.com/grpc/grpc-java/blob/master/SECURITY.md#netty
